const doctors = [
  {
    name: 'Dr. Sarah Johnson',
    specialty: 'cardiology',
    specialties: ['Cardiology', 'Internal Medicine'],
    rating: 4.9,
    experience: '15 years',
    fee: '$150',
    availability: 'Available Today',
    avatar: 'fas fa-user-md',
    photo: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=200&h=200&fit=crop',
    bio: 'Board-certified cardiologist with over 15 years of experience. Specializes in preventive cardiology and heart failure management.',
    education: ['MD, Harvard Medical School', 'Residency, Johns Hopkins Hospital'],
    languages: ['English', 'Spanish'],
    specializations: ['Preventive Cardiology', 'Heart Failure Management'],
  },
  {
    name: 'Dr. Michael Chen',
    specialty: 'dermatology',
    specialties: ['Dermatology', 'General Practice'],
    rating: 4.8,
    experience: '12 years',
    fee: '$120',
    availability: 'Available Tomorrow',
    avatar: 'fas fa-user-md',
    photo: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=200&h=200&fit=crop',
    bio: 'Dermatologist focused on medical and cosmetic dermatology. Expert in skin cancer screening and treatment.',
    education: ['MD, Stanford University School of Medicine', 'Residency, UCSF Medical Center'],
    languages: ['English', 'Mandarin'],
    specializations: ['Skin Cancer Screening', 'Cosmetic Dermatology'],
  },
  {
    name: 'Dr. Emily Rodriguez',
    specialty: 'pediatrics',
    specialties: ['Pediatrics', 'Family Medicine'],
    rating: 4.9,
    experience: '10 years',
    fee: '$100',
    availability: 'Available This Week',
    avatar: 'fas fa-user-md',
    photo: 'https://images.unsplash.com/photo-1594824476967-48c8b964273f?w=200&h=200&fit=crop',
    bio: 'Pediatrician dedicated to child health from infancy through adolescence. Passionate about preventive care and family education.',
    education: ["MD, University of Pennsylvania", "Residency, Children's Hospital of Philadelphia"],
    languages: ['English', 'Spanish'],
    specializations: ['Newborn Care', 'Childhood Immunizations'],
  },
  {
    name: 'Dr. James Patel',
    specialty: 'general practice',
    specialties: ['General Practice', 'Family Medicine'],
    rating: 4.6,
    experience: '8 years',
    fee: '$80',
    availability: 'Available Today',
    avatar: 'fas fa-user-md',
    photo: 'https://images.unsplash.com/photo-1607990281513-2c110a25bd8c?w=200&h=200&fit=crop',
    bio: 'General physician providing whole-person primary care, from routine checkups to managing ongoing conditions.',
    education: ['MBBS, University of Michigan Medical School', 'Residency in Family Medicine, Cleveland Clinic'],
    languages: ['English', 'Hindi'],
    specializations: ['Preventive Care', 'Chronic Disease Management'],
  },
  {
    name: 'Dr. Olivia Turner',
    specialty: 'neurology',
    specialties: ['Neurology', 'Internal Medicine'],
    rating: 4.7,
    experience: '14 years',
    fee: '$170',
    availability: 'Available This Week',
    avatar: 'fas fa-user-md',
    photo: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200&h=200&fit=crop',
    bio: 'Neurologist with a special interest in headache disorders and epilepsy care, blending research with practical treatment plans.',
    education: ['MD, Duke University School of Medicine', 'Residency in Neurology, Mayo Clinic'],
    languages: ['English', 'French'],
    specializations: ['Migraine & Headache Disorders', 'Epilepsy'],
  },
  {
    name: 'Dr. Marcus Webb',
    specialty: 'psychiatry',
    specialties: ['Psychiatry'],
    rating: 4.5,
    experience: '9 years',
    fee: '$130',
    availability: 'Available Tomorrow',
    avatar: 'fas fa-user-md',
    photo: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=200&h=200&fit=crop',
    bio: 'Psychiatrist focused on anxiety and mood disorders, combining medication management with evidence-based therapy referrals.',
    education: ['MD, Yale School of Medicine', 'Residency in Psychiatry, Massachusetts General Hospital'],
    languages: ['English'],
    specializations: ['Anxiety & Mood Disorders', 'Cognitive Behavioral Therapy'],
  },
  {
    name: 'Dr. Grace Kim',
    specialty: 'orthopedics',
    specialties: ['Orthopedics'],
    rating: 4.8,
    experience: '11 years',
    fee: '$140',
    availability: 'Available Today',
    avatar: 'fas fa-user-md',
    photo: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=200&h=200&fit=crop',
    bio: 'Orthopedic surgeon specializing in sports injuries and joint health, helping patients stay active at every age.',
    education: [
      'MD, Columbia University Vagelos College of Physicians and Surgeons',
      'Residency in Orthopedic Surgery, Hospital for Special Surgery',
    ],
    languages: ['English', 'Korean'],
    specializations: ['Sports Medicine', 'Joint Replacement'],
  },
];

module.exports = doctors;
